# Generated by Django 5.2.6 on 2025-09-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=120)),
                ('total_amount', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('equal', 'Equal')], default='equal', max_length=16)),
                ('status', models.CharField(default='open', max_length=16)),
                ('share_token', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organizer_phone'], name='core_bill_organiz_a5d4da_idx'), models.Index(fields=['share_token'], name='core_bill_share_t_bcab97_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('expected_amount', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('mpesa_checkout_request_id', models.CharField(max_length=64, unique=True)),
                ('result_code', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.bill')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.participant')),
            ],
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['bill'], name='core_partic_bill_id_0052bc_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone_number'], name='core_partic_phone_n_8c7469_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('bill', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill'], name='core_paymen_bill_id_79e552_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['participant'], name='core_paymen_partici_2bb496_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='core_paymen_mpesa_c_0b5a5c_idx'),
        ),
    ]
